### ISSUE TITLE
UAE news in Russian/Ukrainian

### ISSUE THREAD

**Issue by emaggy** [fac-17/PFAK-week5#15]
Think United Arab Emirates news is in Russian

[](url)
<img width="1164" alt="Screenshot 2019-08-02 at 10 00 46" src="https://user-images.githubusercontent.com/40627253/62358406-8fe69880-b50c-11e9-8de6-c0278ed6dbc7.png">

**Comment by crianonim** [comment]
You have "ua" (Ukraine) and not "ae" as a value in your index.html
