### ISSUE TITLE
Declaring variables and not using them

### ISSUE THREAD

**Issue by crianonim** [fac-17/PFAK-week5#28]
For example:
`handler.js`: line 5
```javascript
const env = require("dotenv").config();
```
Since you never use `env` you do not need to create a global variable

**Comment by dubhcait** [comment]
ya can just write 

```require("dotenv").config(); ```

Plus further down line 46  const newsKey = process.env.DB_APIKEYNEWS; 
DB_ is usually used for databases, not APIs, it's just naming convention.
