### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by tonylomax** [fac-17/PFAK-week5#31]
Commits are a little unequal, could be addressed when addressing issues?

![Screen Shot 2019-08-02 at 10 27 01](https://user-images.githubusercontent.com/44951051/62360169-24062f00-b510-11e9-884a-2db0173d7690.png)

**Comment by Albadylic** [comment]
![AFGK-commits](https://user-images.githubusercontent.com/43413852/62360566-f79ee280-b510-11e9-83e1-8a0f724ac346.png)
