### ISSUE TITLE
Usage of Data Sets!

### ISSUE THREAD

**Issue by Albadylic** [fac-17/PFAK-week5#37]
I had never even heard of these so kudos for using them! Very useful for your DOM manipulation later on and allows less lines of code in your script.js. Very impressive! :open_mouth: :1st_place_medal: 

I think this would be a cool thing to share in your presentation, I'm sure I'm not the only one not to know about these! :mortar_board:

**Comment by crianonim** [comment]
Agree! These are a very clean and standard way to add data to your elements! Please share with all!
