### ISSUE TITLE
Button Ux

### ISSUE THREAD

**Issue by Oliversw** [fac-17/PFAK-week5#38]
It might be worth looking at the quick select buttons and modifying the styling. Something about them right now doesn't make them feel like 'buttons', which affects the usability of the site.

Something as easy as a small hover animation could help. Otherwise maybe drop shadows, or a background. They look a little bit like just another static section to me as it is. Just a thought!
![Screen Shot 2019-08-02 at 10 44 16 AM](https://user-images.githubusercontent.com/9094166/62361338-bb6c8180-b512-11e9-8ff2-f8be6186bef1.png)

**Comment by Albadylic** [comment]
Adding a hover animation so they turn into rainbow borders matching your button below or the colours of the countries flags could be a way of improving on this.

**Comment by tonylomax** [comment]
Or changing the cursor to pointer on hover 🤜🤛
